version: "3.8"
services:
      
  bookstore-node-typeorm:
    image: bookstore-node-typeorm
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      